"""
Neo4j Client Module
Handles connection to Neo4j AuraDB and executes Cypher queries
"""
from neo4j import GraphDatabase
from typing import List, Dict, Any
from config import NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD, SIMULATION_GRAPH, PRODUCTION_GRAPH
import logging

logger = logging.getLogger(__name__)


class Neo4jClient:
    """Client for Neo4j database operations"""
    
    def __init__(self):
        """Initialize Neo4j driver"""
        self.driver = GraphDatabase.driver(
            NEO4J_URI,
            auth=(NEO4J_USERNAME, NEO4J_PASSWORD)
        )
    
    def close(self):
        """Close the driver connection"""
        self.driver.close()
    
    def get_servers(self, graph_name: str = PRODUCTION_GRAPH) -> List[Dict[str, Any]]:
        """
        Fetch all relevant nodes from Neo4j (Device, Server, or any primary entity)
        Dynamically adapts to whatever schema exists
        
        Args:
            graph_name: Either "prod" or "sim"
        
        Returns:
            List of node dictionaries with properties
        """
        # Query for Server nodes and return all available properties
        query = """
        MATCH (n:Server)
        RETURN n.name as name,
               n.type as type,
               n.risk_score as risk_score,
               n.cvss_score as cvss_score,
               n.blast_radius_count as blast_radius_count,
               n.exploit_available as exploit_available,
               n.attack_vector as attack_vector,
               n.cve_id as cve_id,
               labels(n) as node_type
        LIMIT 100
        """
        
        with self.driver.session() as session:
            result = session.run(query)
            servers = [dict(record) for record in result]
        
        logger.info(f"Fetched {len(servers)} servers from {graph_name} graph")
        return servers
    
    def discover_schema(self) -> Dict[str, Any]:
        """
        Dynamically discover the live Neo4j schema
        
        Returns:
            Dictionary with node labels, relationship types, and sample node properties
        """
        try:
            with self.driver.session() as session:
                # Get all node labels
                labels_result = session.run("CALL db.labels()")
                labels = [record[0] for record in labels_result]
                
                # Get all relationship types
                rel_result = session.run("CALL db.relationshipTypes()")
                relationship_types = [record[0] for record in rel_result]
                
                # Get sample properties per label by querying actual nodes
                node_properties = {}
                for label in labels:
                    try:
                        query = f"MATCH (n:{label}) RETURN keys(n) as props LIMIT 1"
                        result = session.run(query)
                        record = result.single()
                        if record and record["props"]:
                            node_properties[label] = record["props"]
                        else:
                            node_properties[label] = []
                    except Exception as e:
                        logger.warning(f"Could not get properties for {label}: {str(e)}")
                        node_properties[label] = []
                
                schema = {
                    "node_labels": labels,
                    "relationship_types": relationship_types,
                    "node_properties": node_properties
                }
                
                logger.info(f"Schema discovered: {len(labels)} node labels, {len(relationship_types)} relationship types")
                return schema
        
        except Exception as e:
            logger.error(f"Schema discovery failed: {str(e)}")
            return {
                "node_labels": [],
                "relationship_types": [],
                "node_properties": {}
            }
    
    def execute_custom_cypher(self, cypher_query: str, parameters: Dict[str, Any] = None) -> List[Dict[str, Any]]:
        """
        Execute a custom Cypher query generated by LLM
        
        Args:
            cypher_query: The Cypher query to execute
            parameters: Optional parameters for the query
        
        Returns:
            Query results as list of dictionaries
        """
        try:
            with self.driver.session() as session:
                result = session.run(cypher_query, parameters or {})
                results = [dict(record) for record in result]
            
            logger.info(f"Custom Cypher executed, returned {len(results)} results")
            return results
        
        except Exception as e:
            logger.error(f"Cypher execution failed: {str(e)}")
            return []
    
    def get_vulnerabilities_for_servers(self, servers: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Fetch actual vulnerabilities from Neo4j via HAS_VULNERABILITY relationships
        
        Args:
            servers: List of node dictionaries
        
        Returns:
            List of vulnerabilities with their related nodes
        """
        if not servers:
            return []
        
        query = """
        MATCH (n)-[r:HAS_VULNERABILITY]->(v:Vulnerability)
        WHERE n.name IN $node_names
        RETURN n.name as source_name,
               labels(n) as source_type,
               v.name as vuln_name,
               v.cve_id as cve_id,
               v.cvss_score as cvss_score,
               v.attack_vector as attack_vector,
               v.attack_complexity as attack_complexity,
               v.exploit_available as exploit_available,
               v.description as description,
               properties(v) as all_properties
        ORDER BY v.cvss_score DESC
        """
        
        node_names = [s.get('name') for s in servers if s.get('name')]
        
        with self.driver.session() as session:
            result = session.run(query, node_names=node_names)
            vulnerabilities = [dict(record) for record in result]
        
        logger.info(f"Fetched {len(vulnerabilities)} vulnerabilities from Neo4j HAS_VULNERABILITY relationships")
        return vulnerabilities
    
    def get_blast_radius(self, server_name: str, graph_name: str = PRODUCTION_GRAPH) -> List[Dict[str, Any]]:
        """
        Calculate blast radius using Cypher traversal
        Returns all nodes reachable from the compromised node (schema-agnostic)
        
        Args:
            server_name: Name of the compromised node
            graph_name: Graph to query
        
        Returns:
            List of affected nodes
        """
        query = """
        MATCH (start {name: $server_name})
        MATCH (start)-[*1..5]->(affected)
        RETURN DISTINCT affected.name as name,
                        affected.type as type,
                        affected.risk_score as risk_score,
                        labels(affected) as labels
        LIMIT 100
        """
        
        with self.driver.session() as session:
            result = session.run(query, server_name=server_name)
            blast_radius = [dict(record) for record in result]
        
        logger.info(f"Blast radius from {server_name}: {len(blast_radius)} nodes affected")
        return blast_radius
    
    def get_high_criticality_servers(self, graph_name: str = PRODUCTION_GRAPH) -> List[Dict[str, Any]]:
        """
        Fetch high-risk nodes based on risk_score
        
        Args:
            graph_name: Either "prod" or "sim"
        
        Returns:
            List of high-priority nodes
        """
        query = """
        MATCH (n:Server)
        WHERE n.risk_score >= 60
        RETURN n.name as name,
               n.type as type,
               n.risk_score as risk_score,
               n.cvss_score as cvss_score,
               labels(n) as node_type
        ORDER BY n.risk_score DESC
        LIMIT 100
        """
        
        with self.driver.session() as session:
            result = session.run(query)
            nodes = [dict(record) for record in result]
        
        return nodes
    
    def check_connection(self) -> bool:
        """
        Test connection to Neo4j
        
        Returns:
            True if connection successful, False otherwise
        """
        try:
            with self.driver.session() as session:
                result = session.run("RETURN 1")
                result.single()
            return True
        except Exception as e:
            logger.error(f"Neo4j connection failed: {str(e)}")
            return False
