"""
Red Agent Module
Main orchestrator for dynamic attack vector analysis
Flow: Schema Discovery → Gemini-Generated Cypher → Attack Narrative Analysis
No hardcoded queries - all Cypher is dynamically generated by Gemini based on live schema
"""
from typing import List, Dict, Any, Optional
import json
from neo4j_client import Neo4jClient
from llm_client import LLMClient
from config import PRODUCTION_GRAPH, SIMULATION_GRAPH, MAX_ATTACK_VECTORS, CVSS_THRESHOLD
import logging

logger = logging.getLogger(__name__)


class RedAgent:
    """
    Red Agent for dynamic attack vector analysis
    Adapts to any graph schema using schema discovery and Gemini-generated Cypher
    """
    
    def __init__(self):
        """Initialize Red Agent with Neo4j and LLM clients"""
        self.neo4j = Neo4jClient()
        self.llm = LLMClient()
    
    def analyze_attack_vectors(
        self,
        graph_name: str = PRODUCTION_GRAPH,
        focus_server: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Main method to analyze and prioritize attack vectors
        Uses dynamic schema discovery and Gemini-generated Cypher queries
        
        Args:
            graph_name: "prod" or "sim" graph to analyze
            focus_server: Optional specific node to focus on
        
        Returns:
            Structured attack vector analysis with prioritization
        """
        logger.info(f"Red Agent starting dynamic analysis on {graph_name} graph")
        
        try:
            # Step 1: Discover live schema from Neo4j
            logger.info("Step 1: Discovering live Neo4j schema")
            schema = self.neo4j.discover_schema()
            
            if not schema.get("node_labels"):
                logger.error("No node labels found in graph")
                return {
                    "status": "error",
                    "message": "No nodes found in graph - schema is empty",
                    "attack_report": {}
                }
            
            logger.info(f"Schema discovered: {len(schema.get('node_labels', []))} labels, "
                       f"{len(schema.get('relationship_types', []))} relationships")
            
            # Step 2: Use Gemini to generate Cypher query for attack entry point
            logger.info("Step 2: Generating Cypher query via Gemini")
            cypher_query = self._generate_cypher_query(schema)
            
            if not cypher_query:
                logger.error("Failed to generate Cypher query")
                return {
                    "status": "error",
                    "message": "Could not generate Cypher query",
                    "attack_report": {}
                }
            
            logger.info(f"Generated Cypher query (length: {len(cypher_query)} chars)")
            
            # Step 3: Execute the generated Cypher query
            logger.info("Step 3: Executing generated Cypher query")
            cypher_results = self.neo4j.execute_custom_cypher(cypher_query)
            
            if not cypher_results:
                logger.warning("Cypher query returned no results")
                cypher_results = []
            
            logger.info(f"Query returned {len(cypher_results)} results")
            
            # Step 4: Use Gemini to analyze results and generate attack report
            logger.info("Step 4: Generating attack narrative via Gemini")
            attack_report = self._generate_attack_narrative(cypher_results)
            
            # Step 5: Format final output
            result = {
                "status": "success",
                "graph": graph_name,
                "schema_discovered": len(schema.get("node_labels", [])),
                "cypher_executed": True,
                "results_found": len(cypher_results),
                "attack_report": attack_report,
                "raw_query_results": cypher_results[:10] if cypher_results else []  # First 10 for reference
            }
            
            logger.info("Red Agent analysis complete")
            return result
        
        except Exception as e:
            logger.error(f"Red Agent analysis failed: {str(e)}")
            return {
                "status": "error",
                "message": str(e),
                "attack_report": {}
            }
    
    def _generate_cypher_query(self, schema: Dict[str, Any]) -> str:
        """
        Use Gemini to generate a dynamic Cypher query based on live schema
        
        Args:
            schema: The live Neo4j schema (labels, relationships, properties)
        
        Returns:
            Cypher query string, or empty string if generation failed
        """
        try:
            # Format schema for Gemini
            schema_text = self._format_schema_for_llm(schema)
            
            prompt = f"""You are a Neo4j Cypher expert analyzing a banking network graph.
Here is the live banking network graph schema:

{schema_text}

Generate a SINGLE Cypher query that:
1. Finds the highest cvss_score node where exploit_available is true (entry point)
2. From that node, traverses CONNECTS_TO, ROUTES_TO, and RELAYS_TO relationships up to 4 hops
3. Finds all reachable nodes and returns:
   - entry_node name and cvss_score and cve_id
   - Each reachable node name, risk_score, and path relationship type

Requirements:
- Use only existing node labels and relationship types from the schema
- Do NOT use non-existent labels like "Vulnerability" or relationships like "HAS_VULNERABILITY"
- Return only the Cypher query, no explanation
- The query must be executable as-is
- Use DISTINCT to avoid duplicates
- Order by risk_score descending
- LIMIT 100 results

Return ONLY the Cypher code, nothing else. Start with MATCH, end with appropriate RETURN clause."""
            
            response = self.llm.client.generate_content(
                prompt,
                generation_config={
                    "max_output_tokens": 1000,
                    "temperature": 0.3,
                }
            )
            
            cypher_query = response.text.strip()
            
            # Clean up the response - remove markdown code blocks if present
            if cypher_query.startswith("```"):
                cypher_query = cypher_query[cypher_query.find("\n")+1:]
            if cypher_query.endswith("```"):
                cypher_query = cypher_query[:cypher_query.rfind("```")]
            
            logger.info(f"Generated Cypher query from schema (length: {len(cypher_query)})")
            return cypher_query.strip()
        
        except Exception as e:
            logger.error(f"Cypher generation failed: {str(e)}")
            return ""
    
    def _generate_attack_narrative(self, cypher_results: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Use Gemini to analyze Cypher results and generate attack narrative
        
        Args:
            cypher_results: Results from the executed Cypher query
        
        Returns:
            Structured attack report with narrative and analysis
        """
        try:
            # Format results for Gemini
            results_text = json.dumps(cypher_results[:50], indent=2)  # Limit to first 50
            
            prompt = f"""You are a Red Team analyst for a banking network.
Here are the results of a graph traversal showing an attack path through a bank network:

ATTACK PATH RESULTS:
{results_text}

Analyze this attack path and generate a structured red team attack report.

The report MUST include:
- entry_point: Name of the compromised node (highest cvss_score)
- cve_used: The CVE identifier of the initial exploit
- attack_steps: A list where each step has:
  - step: step number
  - action: what the attacker does
  - mitre_technique: MITRE ATT&CK technique (e.g., T1021.006)
  - target_node: which node is compromised in this step
  - result: outcome of this step
- highest_value_target: The most critical node reachable (typically banking infrastructure)
- blast_radius_count: Total number of nodes compromised/reachable
- overall_severity: "CRITICAL", "HIGH", "MEDIUM", or "LOW"
- recommended_defenses: List of immediate defensive actions

Return as valid JSON only, no explanations. Format:
{{
  "entry_point": "...",
  "cve_used": "...",
  "attack_steps": [
    {{"step": 1, "action": "...", "mitre_technique": "...", "target_node": "...", "result": "..."}}
  ],
  "highest_value_target": "...",
  "blast_radius_count": N,
  "overall_severity": "...",
  "recommended_defenses": [...]
}}"""
            
            response = self.llm.client.generate_content(
                prompt,
                generation_config={
                    "max_output_tokens": 2000,
                    "temperature": 0.5,
                }
            )
            
            response_text = response.text.strip()
            
            # Extract JSON from response
            try:
                json_start = response_text.find('{')
                json_end = response_text.rfind('}') + 1
                
                if json_start != -1 and json_end > json_start:
                    json_str = response_text[json_start:json_end]
                    attack_report = json.loads(json_str)
                else:
                    attack_report = {"raw_response": response_text, "parse_error": "No JSON found"}
            
            except json.JSONDecodeError as e:
                logger.error(f"Failed to parse attack narrative JSON: {str(e)}")
                attack_report = {"raw_response": response_text, "parse_error": str(e)}
            
            logger.info("Generated attack narrative")
            return attack_report
        
        except Exception as e:
            logger.error(f"Attack narrative generation failed: {str(e)}")
            return {
                "error": str(e),
                "attack_steps": [],
                "overall_severity": "UNKNOWN"
            }
    
    def _format_schema_for_llm(self, schema: Dict[str, Any]) -> str:
        """
        Format the Neo4j schema as a readable string for LLM consumption
        
        Args:
            schema: Schema dictionary from discover_schema()
        
        Returns:
            Formatted schema string
        """
        lines = []
        
        # Node labels
        lines.append("NODE LABELS:")
        for label in schema.get("node_labels", []):
            lines.append(f"  - {label}")
        
        # Relationship types
        lines.append("\nRELATIONSHIP TYPES:")
        for rel_type in schema.get("relationship_types", []):
            lines.append(f"  - {rel_type}")
        
        # Node properties per label
        lines.append("\nNODE PROPERTIES PER LABEL:")
        for label, properties in schema.get("node_properties", {}).items():
            lines.append(f"  {label}:")
            # Properties can be either strings or dicts (handle both cases)
            for prop in properties:
                if isinstance(prop, dict):
                    lines.append(f"    - {prop.get('property')} ({prop.get('type')})")
                else:
                    # If it's already a string, just use it
                    lines.append(f"    - {prop}")
        
        return "\n".join(lines)
    
    def close(self):
        """Close all client connections"""
        self.neo4j.close()
        logger.info("Red Agent closed")


# Convenience function for direct usage
def run_red_agent_analysis(graph_name: str = PRODUCTION_GRAPH) -> Dict[str, Any]:
    """
    Convenience function to run red agent analysis
    
    Args:
        graph_name: "prod" or "sim"
    
    Returns:
        Analysis results
    """
    agent = RedAgent()
    try:
        result = agent.analyze_attack_vectors(graph_name=graph_name)
        return result
    finally:
        agent.close()
