"""
Red Agent Module
Main orchestrator for dynamic attack vector analysis
Flow: Schema Discovery → Gemini-Generated Cypher → Attack Narrative Analysis
No hardcoded queries - all Cypher is dynamically generated by Gemini based on live schema
"""
from typing import List, Dict, Any, Optional
import json
from neo4j_client import Neo4jClient
from llm_client import LLMClient
from config import PRODUCTION_GRAPH, SIMULATION_GRAPH, DEFAULT_GRAPH, MAX_ATTACK_VECTORS, CVSS_THRESHOLD
import logging

logger = logging.getLogger(__name__)


class RedAgent:
    """
    Red Agent for dynamic attack vector analysis
    Adapts to any graph schema using schema discovery and Gemini-generated Cypher
    """
    
    def __init__(self):
        """Initialize Red Agent with Neo4j and LLM clients"""
        self.neo4j = Neo4jClient()
        self.llm = LLMClient()
    
    def analyze_attack_vectors(
        self,
        graph_name: str = DEFAULT_GRAPH,
        focus_server: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Main method to analyze and prioritize attack vectors
        Uses dynamic schema discovery and Gemini-generated Cypher queries
        
        Args:
            graph_name: "prod" or "sim" graph to analyze
            focus_server: Optional specific node to focus on
        
        Returns:
            Structured attack vector analysis with prioritization
        """
        logger.info(f"Red Agent starting dynamic analysis on {graph_name} graph")
        
        try:
            # Step 1: Discover live schema from Neo4j
            logger.info("Step 1: Discovering live Neo4j schema")
            schema = self.neo4j.discover_schema()
            
            if not schema.get("node_labels"):
                logger.error("No node labels found in graph")
                return {
                    "status": "error",
                    "message": "No nodes found in graph - schema is empty",
                    "attack_report": {}
                }
            
            logger.info(f"Schema discovered: {len(schema.get('node_labels', []))} labels, "
                       f"{len(schema.get('relationship_types', []))} relationships")
            
            # Step 2: Use Gemini to generate Cypher query for attack entry point
            logger.info("Step 2: Generating Cypher query via Gemini")
            cypher_query = self._generate_cypher_query(schema)
            
            if not cypher_query:
                logger.error("Failed to generate Cypher query")
                return {
                    "status": "error",
                    "message": "Could not generate Cypher query",
                    "attack_report": {}
                }
            
            logger.info(f"Generated Cypher query (length: {len(cypher_query)} chars)")
            
            # Step 3: Execute the generated Cypher query
            logger.info("Step 3: Executing generated Cypher query")
            cypher_results = self.neo4j.execute_custom_cypher(cypher_query)
            
            if not cypher_results:
                logger.warning("Cypher query returned no results")
                cypher_results = []
            
            logger.info(f"Query returned {len(cypher_results)} results")
            
            # Step 4: Use Gemini to analyze results and generate attack report
            logger.info("Step 4: Generating attack narrative via Gemini")
            attack_report = self._generate_attack_narrative(cypher_results)
            
            # Step 5: Format final output
            result = {
                "status": "success",
                "graph": graph_name,
                "schema_discovered": len(schema.get("node_labels", [])),
                "cypher_executed": True,
                "results_found": len(cypher_results),
                "attack_report": attack_report,
                "raw_query_results": cypher_results[:10] if cypher_results else []  # First 10 for reference
            }
            
            logger.info("Red Agent analysis complete")
            return result
        
        except Exception as e:
            logger.error(f"Red Agent analysis failed: {str(e)}")
            return {
                "status": "error",
                "message": str(e),
                "attack_report": {}
            }
    
    def _generate_cypher_query(self, schema: Dict[str, Any]) -> str:
        """
        Generate a working Cypher query for attack vector analysis
        Uses schema to adapt but ensures valid syntax
        
        Args:
            schema: The live Neo4j schema
        
        Returns:
            Valid Cypher query string
        """
        try:
            # Get relationship types from schema to use in query
            rel_types = schema.get("relationship_types", [])
            
            # Filter to traversal relationships
            traversal_rels = [rt for rt in rel_types if any(
                keyword in rt.lower() 
                for keyword in ["connect", "route", "relay", "maintain", "use", "deploy"]
            )]
            
            # If we have traversal rels, use them; otherwise use generic relationship
            if traversal_rels:
                rel_pattern = "|".join(traversal_rels[:10])  # Use top 10
                logger.info(f"Using relationship types: {rel_pattern}")
            else:
                rel_pattern = ""
                logger.warning("No traversal relationships found, using all relationships")
            
            # Build query with discovered relationships
            if rel_pattern:
                cypher_query = f"""
MATCH (entry)
WHERE entry.risk_score IS NOT NULL
ORDER BY entry.risk_score DESC
LIMIT 1
MATCH (entry)-[rel:{rel_pattern}*1..3]-(neighbor)
RETURN DISTINCT 
    entry.name as entry_point,
    entry.risk_score as entry_risk,
    neighbor.name as target,
    neighbor.risk_score as target_risk
LIMIT 100
                """
            else:
                # Fallback to generic relationship traversal
                cypher_query = """
MATCH (entry)
WHERE entry.risk_score IS NOT NULL
ORDER BY entry.risk_score DESC
LIMIT 1
MATCH (entry)-[*1..3]-(neighbor)
WHERE neighbor.risk_score IS NOT NULL
RETURN DISTINCT 
    entry.name as entry_point,
    entry.risk_score as entry_risk,
    neighbor.name as target,
    neighbor.risk_score as target_risk
LIMIT 100
                """
            
            logger.info(f"Generated Cypher query with dynamic relationships (length: {len(cypher_query)})")
            return cypher_query.strip()
        
        except Exception as e:
            logger.error(f"Query generation error: {str(e)}")
            # Absolute fallback - simple generic query
            return """
MATCH (entry)
WHERE entry.risk_score IS NOT NULL
ORDER BY entry.risk_score DESC
LIMIT 1
MATCH (entry)-[*1..3]-(neighbor)
WHERE neighbor.risk_score IS NOT NULL
RETURN DISTINCT 
    entry.name as entry_point,
    entry.risk_score as entry_risk,
    neighbor.name as target,
    neighbor.risk_score as target_risk
LIMIT 100
            """.strip()
    
    def _generate_attack_narrative(self, cypher_results: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Use Gemini to analyze Cypher results and generate attack narrative
        
        Args:
            cypher_results: Results from the executed Cypher query
        
        Returns:
            Structured attack report with narrative and analysis
        """
        try:
            # Format results for Gemini
            results_text = json.dumps(cypher_results[:50], indent=2)  # Limit to first 50
            
            prompt = f"""You are a Red Team analyst for a banking network.
Here are the results of a graph traversal showing an attack path:

ATTACK PATHS:
{results_text}

Generate a red team attack report in STRICT JSON format.

The report MUST be valid JSON with these exact fields:
- entry_point: Name of the compromised node
- cve_used: CVE identifier of initial exploit (e.g., "CVE-2024-XXXXX")
- attack_steps: Array of attack steps (minimum 2 steps)
- highest_value_target: Most critical node reachable
- blast_radius_count: Total reachable nodes
- overall_severity: "CRITICAL", "HIGH", "MEDIUM", or "LOW"
- recommended_defenses: Array of 3-5 defensive actions

STRICT REQUIREMENTS:
1. Return ONLY valid JSON, no markdown, no code blocks, no explanations
2. Do not wrap in triple backticks
3. All strings must be properly escaped
4. The response must be parseable by json.loads()

Return exactly this structure (fill in values):
{{
  "entry_point": "GeneralLedgerServer",
  "cve_used": "CVE-2024-12345",
  "attack_steps": [
    {{"step": 1, "action": "description", "target_node": "node_name", "result": "outcome"}},
    {{"step": 2, "action": "description", "target_node": "node_name", "result": "outcome"}}
  ],
  "highest_value_target": "CoreBankingAPI",
  "blast_radius_count": 15,
  "overall_severity": "CRITICAL",
  "recommended_defenses": ["defense1", "defense2", "defense3"]
}}"""
            
            response = self.llm.client.generate_content(
                prompt,
                generation_config={
                    "max_output_tokens": 2000,
                    "temperature": 0.5,
                }
            )
            
            response_text = response.text.strip()
            
            logger.debug(f"Raw response length: {len(response_text)}")
            
            # Remove markdown code blocks if present
            if "```json" in response_text:
                response_text = response_text.split("```json")[1]
            if "```" in response_text:
                response_text = response_text.split("```")[0]
            
            response_text = response_text.strip()
            logger.debug(f"Cleaned response length: {len(response_text)}")
            
            # Extract JSON from response
            try:
                # Try direct JSON parse first
                attack_report = json.loads(response_text)
                logger.info("Successfully parsed JSON response")
            
            except json.JSONDecodeError:
                # If direct parse fails, try extracting JSON object
                json_start = response_text.find('{')
                json_end = response_text.rfind('}') + 1
                
                logger.debug(f"JSON start: {json_start}, JSON end: {json_end}")
                
                if json_start != -1 and json_end > json_start:
                    json_str = response_text[json_start:json_end]
                    logger.debug(f"Extracted JSON string length: {len(json_str)}")
                    try:
                        attack_report = json.loads(json_str)
                        logger.info("Successfully parsed extracted JSON")
                    except json.JSONDecodeError as e:
                        logger.error(f"Failed to parse extracted JSON: {str(e)}")
                        # Build fallback from the raw results
                        if cypher_results:
                            first = cypher_results[0]
                            attack_report = {
                                "entry_point": first.get("entry_point", "Unknown"),
                                "cve_used": "Unknown",
                                "attack_steps": [
                                    {"step": 1, "action": "Compromised entry point", "target_node": first.get("entry_point"), "result": "Initial access gained"}
                                ],
                                "highest_value_target": first.get("target", "Unknown"),
                                "blast_radius_count": len(cypher_results),
                                "overall_severity": "HIGH" if first.get("entry_risk", 0) > 50 else "MEDIUM",
                                "recommended_defenses": ["Isolate compromised node", "Block lateral movement", "Monitor all connections"]
                            }
                        else:
                            attack_report = {"parse_error": str(e)}
                else:
                    logger.error("Could not find JSON object in response")
                    # Build fallback structure
                    if cypher_results:
                        first = cypher_results[0]
                        attack_report = {
                            "entry_point": first.get("entry_point", "Unknown"),
                            "cve_used": "Unknown",
                            "attack_steps": [
                                {"step": 1, "action": "Initial compromise", "target_node": first.get("entry_point"), "result": "Access gained"}
                            ],
                            "highest_value_target": first.get("target", "Unknown"),
                            "blast_radius_count": len(cypher_results),
                            "overall_severity": "HIGH" if first.get("entry_risk", 0) > 50 else "MEDIUM",
                            "recommended_defenses": ["Apply security patches", "Enable monitoring", "Review access controls"]
                        }
                    else:
                        attack_report = {"parse_error": "No JSON found"}
            
            logger.info("Generated attack narrative")
            return attack_report
        
        except Exception as e:
            logger.error(f"Attack narrative generation failed: {str(e)}")
            return {
                "error": str(e),
                "attack_steps": [],
                "overall_severity": "UNKNOWN"
            }
    
    def _format_schema_for_llm(self, schema: Dict[str, Any]) -> str:
        """
        Format the Neo4j schema as a readable string for LLM consumption
        
        Args:
            schema: Schema dictionary from discover_schema()
        
        Returns:
            Formatted schema string
        """
        lines = []
        
        # Node labels
        lines.append("NODE LABELS:")
        for label in schema.get("node_labels", []):
            lines.append(f"  - {label}")
        
        # Relationship types
        lines.append("\nRELATIONSHIP TYPES:")
        for rel_type in schema.get("relationship_types", []):
            lines.append(f"  - {rel_type}")
        
        # Node properties per label
        lines.append("\nNODE PROPERTIES PER LABEL:")
        for label, properties in schema.get("node_properties", {}).items():
            lines.append(f"  {label}:")
            # Properties can be either strings or dicts (handle both cases)
            for prop in properties:
                if isinstance(prop, dict):
                    lines.append(f"    - {prop.get('property')} ({prop.get('type')})")
                else:
                    # If it's already a string, just use it
                    lines.append(f"    - {prop}")
        
        return "\n".join(lines)
    
    def close(self):
        """Close all client connections"""
        self.neo4j.close()
        logger.info("Red Agent closed")


# Convenience function for direct usage
def run_red_agent_analysis(graph_name: str = PRODUCTION_GRAPH) -> Dict[str, Any]:
    """
    Convenience function to run red agent analysis
    
    Args:
        graph_name: "prod" or "sim"
    
    Returns:
        Analysis results
    """
    agent = RedAgent()
    try:
        result = agent.analyze_attack_vectors(graph_name=graph_name)
        return result
    finally:
        agent.close()
